### ISSUE TITLE
after horizontal scrolling content get reset

### ISSUE THREAD

**Issue by kaushalraykar** [InQBarna/TableFixHeaders#134]
hello in my column no 3 their is a edit text, when i enter the value in edit text and perfom horizontal scrolling edit text value get reset to 0.

**Comment by BraisGabin** [comment]
TFH doesn't save the state of the views. So if you have an `EditText` in it you should save the data that the user writes as soon as it writes it. Otherwise you are going to have this problem. Or other problems like values repeated on vertical scroll.

You could rewrite TFH to save and restore the view state... But I think that even the `RecyclerView` doesn't do that so it doesn't seem a good idea.
